"""Blind replay: qwen3.5:9b vs gemma4:e4b on real Moltbook verify_solve challenges.

Diagnoses whether the observed llm_reason (66.7%) / llm_extract (16.1%) wrong-answer
rate against code_parse's 1.8% (measured 2026-06-28..07-01, gemma4:e4b-only period,
n=252 in logs/verification-audit.jsonl) is a gemma4:e4b model characteristic or a
prompt/guard design gap common to any model. Read-only, offline: NO Moltbook network
calls (submit_verification / record_verification_audit are never invoked), so it
cannot consume the real platform's rate-limited /verify quota and cannot write to
verification-audit.jsonl (that corpus stays untouched for future re-measurement).
Does not call configure_llm()/Agent() -- verify_solve's system prompts are passed
explicitly by solve_challenge_result() and never touch the identity/skills/rules
system-prompt builder, so this script needs none of that and, as a side effect,
never touches llm-calls-*.jsonl telemetry either (_telemetry_dir stays None).

Design note (the reason a naive "replay all verify_success=True rows through both
models" comparison would be WRONG): telemetry (caller=moltbook.verify_solve in
logs/llm-calls-*.jsonl) shows qwen3.5:9b only served this caller on 2026-06-28
before the gemma cutover (~12:39 UTC that day, matching the ADR-0069 swap); every
row from 2026-06-29 onward was generated by gemma4:e4b. Comparing both models
against the full verify_success=True set would mostly be gemma re-solving its own
past answers (a self-consistency check dressed up as a fair fight). Instead:
  - primary metric: qwen's BLIND replay accuracy on rows gemma actually solved
    (gemma has never "seen" these answers be produced by itself in this run)
  - secondary metric: gemma's blind replay accuracy on the few rows qwen actually
    solved (small n, 2026-06-28 morning only -- reported but not decision-driving)
  - self-consistency floor: each model's agreement with its OWN historical answer,
    to calibrate how much of any cross-model gap is real vs. sampling/decoding noise

Attribution join: for each audit row, recompute solve_challenge_result's own
prompt string via _challenge_prompt(challenge_text) and hash it exactly like
core/llm.py's telemetry does (hashlib.sha256(prompt.encode("utf-8")).hexdigest()[:12]),
then match against llm-calls-*.jsonl rows with caller=="moltbook.verify_solve" and
a num_predict tier consistent with the audit row's solver_path (512 -> llm_extract,
{3000, 5000} -> llm_reason -- the two solver stages share one prompt string, so
num_predict is what disambiguates which stage's telemetry row this is). Ties are
broken by timestamp proximity to the audit row itself.

Excludes code_parse rows entirely (110/252): deterministic, model-independent, so
replaying them tells us nothing about model choice.
verify_success=False rows (34/252) have no known-correct answer and are reported
only as exploratory context, never as accuracy denominator.

Usage:
    cd <repo root>
    uv run python docs/evidence/verify-solve-model-compare-20260701/replay_qwen_vs_gemma.py --pilot
    uv run python docs/evidence/verify-solve-model-compare-20260701/replay_qwen_vs_gemma.py --full | tee results.txt

Memory safety: qwen(6.6GB) + gemma(9.6GB) > 16GB RAM. `ollama stop` the previous
model before switching (same pattern as docs/evidence/adr-0068/ab_gemma_think-20260628.py).
Run outside the 0/6/12/18 JST scheduled agent session window.
"""

from __future__ import annotations

import argparse
import base64
import glob
import hashlib
import json
import os
import subprocess
import sys
import time
from decimal import Decimal, InvalidOperation
from pathlib import Path


def _find_repo_root() -> Path:
    for parent in Path(__file__).resolve().parents:
        if (parent / "src" / "contemplative_agent").is_dir():
            return parent
    raise RuntimeError("Could not locate repo root (src/contemplative_agent not found)")


REPO = _find_repo_root()
sys.path.insert(0, str(REPO / "src"))

from contemplative_agent.adapters.moltbook.config import EPISODE_LOG_DIR  # noqa: E402
from contemplative_agent.adapters.moltbook.verification import (  # noqa: E402
    _challenge_prompt,
    solve_challenge_result,
)

QWEN = "qwen3.5:9b"
GEMMA = "gemma4:e4b"
AUDIT_PATH = EPISODE_LOG_DIR / "verification-audit.jsonl"


def _load_audit_rows() -> list[dict]:
    rows = []
    for line in AUDIT_PATH.read_text().splitlines():
        line = line.strip()
        if line:
            rows.append(json.loads(line))
    return rows


def _load_verify_solve_telemetry() -> list[dict]:
    rows = []
    for path in sorted(glob.glob(str(EPISODE_LOG_DIR / "llm-calls-*.jsonl"))):
        for line in Path(path).read_text().splitlines():
            line = line.strip()
            if not line:
                continue
            d = json.loads(line)
            if d.get("caller") == "moltbook.verify_solve":
                rows.append(d)
    return rows


def _num_predict_tier(solver_path: str) -> set[int]:
    return {512} if solver_path == "llm_extract" else {3000, 5000}


def _attribute_model(audit_row: dict, challenge_text: str, telemetry: list[dict]) -> str | None:
    """Return the model that actually produced this audit row's answer, or None."""
    prompt = _challenge_prompt(challenge_text)
    key = hashlib.sha256(prompt.encode("utf-8")).hexdigest()[:12]
    tiers = _num_predict_tier(audit_row["solver_path"])
    candidates = [
        t for t in telemetry
        if t.get("prompt_sha256") == key and t.get("num_predict") in tiers
    ]
    if not candidates:
        return None
    if len(candidates) == 1:
        return candidates[0].get("model")
    # Tie-break: closest timestamp to the audit row.
    audit_ts = audit_row["ts"]
    candidates.sort(key=lambda t: abs(_ts_diff(t.get("ts", ""), audit_ts)))
    return candidates[0].get("model")


def _ts_diff(a: str, b: str) -> float:
    from datetime import datetime

    try:
        return (
            datetime.fromisoformat(a) - datetime.fromisoformat(b)
        ).total_seconds()
    except ValueError:
        return float("inf")


def _decode(challenge_b64: str) -> str:
    return base64.b64decode(challenge_b64).decode("utf-8", errors="replace")


def _numbers_equal(a: str | None, b: str | None) -> bool:
    if a is None or b is None:
        return False
    try:
        return Decimal(a) == Decimal(b)
    except InvalidOperation:
        return a == b


def _prepare_rows() -> dict:
    """Load, decode, and attribute every non-code_parse audit row once."""
    audit_rows = [r for r in _load_audit_rows() if r["solver_path"] != "code_parse"]
    telemetry = _load_verify_solve_telemetry()
    prepared = []
    unattributed = 0
    for row in audit_rows:
        challenge_text = _decode(row["challenge_b64"])
        model = _attribute_model(row, challenge_text, telemetry)
        if model is None:
            unattributed += 1
        prepared.append(
            {
                "ts": row["ts"],
                "challenge_text": challenge_text,
                "solver_path": row["solver_path"],
                "historical_answer": row["answer"],
                "verify_success": row["verify_success"],
                "attributed_model": model,
            }
        )
    print(
        f"[prepare] {len(prepared)} non-code_parse rows loaded, "
        f"{unattributed} unattributed (no telemetry match)",
        file=sys.stderr,
    )
    return {
        "gemma_solved": [
            r for r in prepared
            if r["attributed_model"] == GEMMA and r["verify_success"]
        ],
        "qwen_solved": [
            r for r in prepared
            if r["attributed_model"] == QWEN and r["verify_success"]
        ],
        "all": prepared,
    }


def _switch_model(model: str, previous: str | None) -> None:
    if previous is not None and previous != model:
        print(f"[switch] ollama stop {previous}", file=sys.stderr, flush=True)
        subprocess.run(["ollama", "stop", previous], check=False)
    os.environ["OLLAMA_MODEL"] = model


def _replay(rows: list[dict], model: str) -> list[dict]:
    results = []
    for i, row in enumerate(rows):
        t0 = time.monotonic()
        result = solve_challenge_result(row["challenge_text"])
        dt = time.monotonic() - t0
        match = _numbers_equal(result.answer, row["historical_answer"])
        results.append(
            {
                "i": i,
                "ts": row["ts"],
                "historical_answer": row["historical_answer"],
                "historical_solver_path": row["solver_path"],
                "replay_answer": result.answer,
                "replay_solver_path": result.solver_path,
                "matches_historical": match,
                "sec": round(dt, 1),
            }
        )
        print(
            f"[{model}] {i+1}/{len(rows)}: hist={row['historical_answer']} "
            f"replay={result.answer} match={match} ({dt:.1f}s)",
            file=sys.stderr,
            flush=True,
        )
    return results


def _summarize(label: str, results: list[dict]) -> dict:
    n = len(results)
    matched = sum(1 for r in results if r["matches_historical"])
    return {
        "label": label,
        "n": n,
        "matched": matched,
        "accuracy": round(matched / n, 3) if n else None,
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--pilot", action="store_true", help="~25-row pilot instead of full 142-row run")
    args = parser.parse_args()

    data = _prepare_rows()
    gemma_solved = data["gemma_solved"]
    qwen_solved = data["qwen_solved"]
    print(
        f"[prepare] gemma_solved={len(gemma_solved)} qwen_solved={len(qwen_solved)}",
        file=sys.stderr,
    )

    if args.pilot:
        gemma_solved = gemma_solved[:25]
        qwen_solved = qwen_solved[:10]

    summary = []
    prev_model = None

    # Primary metric: qwen blind-replays gemma's actual solves.
    _switch_model(QWEN, prev_model)
    prev_model = QWEN
    print(f"[warmup] {QWEN}", file=sys.stderr, flush=True)
    if gemma_solved:
        solve_challenge_result(gemma_solved[0]["challenge_text"])
    qwen_on_gemma = _replay(gemma_solved, "qwen_on_gemma_solved")
    summary.append(_summarize("qwen_blind_replay_of_gemma_solved (PRIMARY)", qwen_on_gemma))

    # Self-consistency floor for qwen (on the rows it originally solved).
    qwen_self = _replay(qwen_solved, "qwen_self_consistency") if qwen_solved else []
    if qwen_self:
        summary.append(_summarize("qwen_self_consistency_floor", qwen_self))

    # Secondary metric + gemma self-consistency floor.
    _switch_model(GEMMA, prev_model)
    prev_model = GEMMA
    print(f"[warmup] {GEMMA}", file=sys.stderr, flush=True)
    if qwen_solved:
        solve_challenge_result(qwen_solved[0]["challenge_text"])
    gemma_on_qwen = _replay(qwen_solved, "gemma_on_qwen_solved") if qwen_solved else []
    if gemma_on_qwen:
        summary.append(_summarize("gemma_blind_replay_of_qwen_solved (secondary, small n)", gemma_on_qwen))

    gemma_self = _replay(gemma_solved, "gemma_self_consistency")
    summary.append(_summarize("gemma_self_consistency_floor", gemma_self))

    print("\n===RESULTS_JSON===")
    print(
        json.dumps(
            {
                "summary": summary,
                "detail": {
                    "qwen_on_gemma_solved": qwen_on_gemma,
                    "qwen_self_consistency": qwen_self,
                    "gemma_on_qwen_solved": gemma_on_qwen,
                    "gemma_self_consistency": gemma_self,
                },
            },
            ensure_ascii=False,
            indent=2,
        )
    )


if __name__ == "__main__":
    main()
