"""Rules distillation: synthesize behavioral skills into universal rules.

Two-stage LLM pipeline (ADR-0008): free-form extraction → structured Markdown.
Input: skills/*.md files generated by ``insight``.
Human in the loop — this command is never auto-scheduled.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from datetime import date, datetime, timezone
from pathlib import Path
from typing import List, Optional, Tuple, Union

from .insight import _extract_title, _slugify
from .llm import generate, get_distill_system_prompt, validate_identity_content
from .prompts import RULES_DISTILL_PROMPT, RULES_DISTILL_REFINE_PROMPT

logger = logging.getLogger(__name__)

MIN_SKILLS_REQUIRED = 3
BATCH_SIZE = 10


@dataclass(frozen=True)
class RuleResult:
    """A single generated rule ready for approval."""

    text: str
    filename: str
    target_path: Path


@dataclass(frozen=True)
class RulesDistillResult:
    """Result of a successful rules distillation."""

    rules: Tuple[RuleResult, ...]
    dropped_count: int
    rules_dir: Path


def _strip_frontmatter(text: str) -> str:
    """Strip YAML frontmatter (``---`` delimited) from Markdown text."""
    lines = text.split("\n")
    if not lines or lines[0].strip() != "---":
        return text
    for i, line in enumerate(lines[1:], start=1):
        if line.strip() == "---":
            return "\n".join(lines[i + 1 :]).lstrip("\n")
    return text


def _read_skills(skills_dir: Path, since: Optional[str] = None) -> List[str]:
    """Read skill file contents from *skills_dir*.

    Args:
        skills_dir: Directory containing ``*.md`` skill files.
        since: ISO timestamp — only include files modified after this time.

    Returns:
        List of skill file body texts (frontmatter stripped).
    """
    if not skills_dir.is_dir():
        return []

    cutoff: Optional[float] = None
    if since:
        try:
            cutoff = datetime.fromisoformat(since).timestamp()
        except ValueError:
            logger.warning("Invalid since timestamp %r, reading all skills", since)

    skills: List[str] = []
    for p in sorted(skills_dir.glob("*.md")):
        if p.name.startswith("."):
            continue
        if cutoff is not None and p.stat().st_mtime < cutoff:
            continue
        try:
            body = _strip_frontmatter(p.read_text(encoding="utf-8")).strip()
            if body:
                skills.append(body)
        except OSError:
            logger.warning("Could not read skill file %s", p)
    return skills


def _extract_rules(skill_texts: List[str]) -> Optional[str]:
    """Extract behavioral rules from skill texts via 2-stage LLM pipeline.

    Stage 1: Free-form extraction with distill system prompt as lens.
    Stage 2: Refine into structured Markdown.
    """
    prompt = RULES_DISTILL_PROMPT.format(
        patterns="\n\n---\n\n".join(skill_texts),
    )

    raw = generate(prompt, system=get_distill_system_prompt(), max_length=4000)
    if raw is None:
        logger.warning("Stage 1 (extraction) failed.")
        return None

    refine_prompt = RULES_DISTILL_REFINE_PROMPT.format(raw_output=raw)
    result = generate(refine_prompt, max_length=3000)
    if result is None:
        logger.warning("Stage 2 (refinement) failed.")
        return None

    if _extract_title(result) is None:
        logger.warning("Rules extraction has no title (# line). Dropping.")
        logger.debug("Raw LLM output (first 200 chars): %.200s", result)
        return None

    return result


def _read_last_run(rules_dir: Optional[Path]) -> Optional[str]:
    """Read the timestamp of the last rules-distill run."""
    if rules_dir is None:
        return None
    marker = rules_dir / ".last_rules_distill"
    if marker.exists():
        return marker.read_text(encoding="utf-8").strip()
    return None


def _write_last_run(rules_dir: Path) -> None:
    """Record the current timestamp as the last rules-distill run."""
    rules_dir.mkdir(parents=True, exist_ok=True)
    marker = rules_dir / ".last_rules_distill"
    marker.write_text(
        datetime.now(timezone.utc).isoformat(timespec="minutes") + "\n",
        encoding="utf-8",
    )


def distill_rules(
    skills_dir: Optional[Path] = None,
    rules_dir: Optional[Path] = None,
    full: bool = False,
) -> Union[str, RulesDistillResult]:
    """Distill universal behavioral rules from accumulated skill files.

    Two-stage pipeline per batch: free-form extraction → structured Markdown.
    Reads skills/*.md generated by ``insight``.

    File writing is the caller's responsibility (ADR-0012 approval gate).

    Args:
        skills_dir: Directory containing skill files (``*.md``).
        rules_dir: Directory for rule files (used for incremental tracking).
        full: If True, process all skills instead of only new ones.

    Returns:
        RulesDistillResult on success, or error message string.
    """
    if skills_dir is None:
        return "No skills directory provided."

    since: Optional[str] = None
    if not full:
        since = _read_last_run(rules_dir)
        if since:
            logger.info("Incremental mode: reading skills modified since %s", since)

    skill_texts = _read_skills(skills_dir, since=since)

    if not since and not full:
        logger.info("No previous rules-distill run found, processing all %d skills", len(skill_texts))

    if len(skill_texts) < MIN_SKILLS_REQUIRED:
        return (
            f"Insufficient skills ({len(skill_texts)}/{MIN_SKILLS_REQUIRED}). "
            f"Universal principles require a critical mass of behavioral skills."
        )

    batches = [
        skill_texts[i : i + BATCH_SIZE]
        for i in range(0, len(skill_texts), BATCH_SIZE)
    ]
    if len(batches) > 1 and len(batches[-1]) < MIN_SKILLS_REQUIRED:
        batches[-2].extend(batches[-1])
        batches.pop()

    logger.info(
        "Processing %d skills in %d batches", len(skill_texts), len(batches)
    )

    rule_results: List[RuleResult] = []
    dropped_count = 0

    for batch_idx, batch in enumerate(batches):
        logger.info(
            "Batch %d/%d: %d skills", batch_idx + 1, len(batches), len(batch)
        )

        rules_text = _extract_rules(batch)
        if rules_text is None:
            logger.warning("Batch %d/%d: extraction failed", batch_idx + 1, len(batches))
            dropped_count += 1
            continue

        if not validate_identity_content(rules_text):
            logger.warning("Batch %d/%d: forbidden pattern detected", batch_idx + 1, len(batches))
            dropped_count += 1
            continue

        title = _extract_title(rules_text) or ""
        slug = _slugify(title)
        if not slug:
            logger.warning("Batch %d/%d: empty slug, dropping", batch_idx + 1, len(batches))
            dropped_count += 1
            continue

        today = date.today().strftime("%Y%m%d")
        filename = f"{slug}-{today}.md"

        if rules_dir is not None:
            file_path = rules_dir / filename
            if not file_path.resolve().is_relative_to(rules_dir.resolve()):
                logger.error("Rule path escape attempt: %s", file_path)
                dropped_count += 1
                continue
        else:
            file_path = Path(filename)

        rule_results.append(RuleResult(
            text=rules_text,
            filename=filename,
            target_path=file_path,
        ))

    if not rule_results:
        return "Failed to extract rules from skills."

    return RulesDistillResult(
        rules=tuple(rule_results),
        dropped_count=dropped_count,
        rules_dir=rules_dir or Path("."),
    )
